# Project: TRPG
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../fightSystem.o ../game.o ../inventory.o ../main.o ../mobs.o ../player.o ../skill.o ../dungeon_tutorial.o ../puzzle_stack.o
LINKOBJ  = ../fightSystem.o ../game.o ../inventory.o ../main.o ../mobs.o ../player.o ../skill.o ../dungeon_tutorial.o ../puzzle_stack.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = TRPG.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

../fightSystem.o: ../fightSystem.c
	$(CC) -c ../fightSystem.c -o ../fightSystem.o $(CFLAGS)

../game.o: ../game.c
	$(CC) -c ../game.c -o ../game.o $(CFLAGS)

../inventory.o: ../inventory.c
	$(CC) -c ../inventory.c -o ../inventory.o $(CFLAGS)

../main.o: ../main.c
	$(CC) -c ../main.c -o ../main.o $(CFLAGS)

../mobs.o: ../mobs.c
	$(CC) -c ../mobs.c -o ../mobs.o $(CFLAGS)

../player.o: ../player.c
	$(CC) -c ../player.c -o ../player.o $(CFLAGS)

../skill.o: ../skill.c
	$(CC) -c ../skill.c -o ../skill.o $(CFLAGS)

../dungeon_tutorial.o: ../dungeon_tutorial.c
	$(CC) -c ../dungeon_tutorial.c -o ../dungeon_tutorial.o $(CFLAGS)

../puzzle_stack.o: ../puzzle_stack.c
	$(CC) -c ../puzzle_stack.c -o ../puzzle_stack.o $(CFLAGS)
