/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Controladores.ControladorVendas;
import classes.Cartao;
import classes.Cheque;
import classes.Dinheiro;
import classes.Venda;
import java.awt.Frame;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Eymar Lima
 */
public class VPTDP_Completo extends javax.swing.JDialog {

    DefaultTableModel dTM;
 
    
    public VPTDP_Completo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dTM = (DefaultTableModel) jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoExibir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ComboBox = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        BotaoExibir.setText("Exibir Itens");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vendas Por Tipo De Pagamento Detalhado");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1436319637_view_detailed.png"))); // NOI18N
        jLabel1.setText("Vendas Por Tipo De Pagamento Detalhado");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tipo de Pagamento:");

        ComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dinheiro", "Cartão", "Cheque" }));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1436409573_icon-40-clipboard-list.png"))); // NOI18N
        jButton2.setText("Listar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número da nota", "Nome do Cliente", "CPF do Cliente", "Data", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1436243313_arrow-back.png"))); // NOI18N
        jButton11.setText("Voltar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("*Clique na venda para exibir os itens.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addGap(257, 257, 257))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ComboBox)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selected = jTable1.getSelectedRow();
        if(selected == -1)return;
        else{
            Venda[] vendas;
            ControladorVendas control = new ControladorVendas();
            try {
                vendas = control.getVendas();
                if(vendas == null)return;
                
                
                
                TabelaItens table = new TabelaItens((Frame) this.getParent(),true,vendas[Integer.parseInt((String) jTable1.getValueAt(selected, 0))]);
                table.setLocationRelativeTo(this);
                table.toFront();
                table.setVisible(true);
                
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(VPTDP_Completo.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Verifica qual tipo de pagamento o usuário solicitou e exibe os dados relativos as vendas desse tipo
        
        int select = ComboBox.getSelectedIndex();
        ControladorVendas control = new ControladorVendas();
        
        for(int i = dTM.getRowCount()-1;i>=0;i--){
            dTM.removeRow(i);
        }
        
        try {
            Venda vendas[] = control.getVendas();
            if(vendas == null){
                JOptionPane.showMessageDialog(null,"Não Existem Vendas Cadastradas!");
                return;
            }
            
            switch(select){//Switch para exibir os dados de acordo com a entrada do usuario
                case 0:{
                    //dinheiro;
                    for(int i =0;i<vendas.length;i++){
                        if(vendas[i].getTipoPgto() instanceof Dinheiro){
                            this.addDadoNaTabela(vendas[i], 1);
                        }
                    }
                    String coluna [] = {"Número Da Nota","Nome do Cliente", "CPF do Cliente", "Data da Compra", "", ""};
                    dTM.setColumnIdentifiers(coluna);
                    break;
                }
                case 1:{
                    //cartão;
                    for(int i =0;i<vendas.length;i++){
                        if(vendas[i].getTipoPgto() instanceof Cartao){
                            this.addDadoNaTabela(vendas[i], 2);
                        }
                    }
                    String coluna [] = {"Número Da Nota","Nome do Cliente", "CPF do Cliente", "Data da Compra", "Titular do Cartão", "Número do Cartão"};
                    dTM.setColumnIdentifiers(coluna);
                    break;
                }
                case 2:{
                    //cheque;
                    for(int i =0;i<vendas.length;i++){
                        if(vendas[i].getTipoPgto() instanceof Cheque){
                            this.addDadoNaTabela(vendas[i], 3);
                        }
                    }
                    String coluna [] = {"Número Da Nota","Nome do Cliente", "CPF do Cliente", "Data da Compra", "Nome do Emissor", "Número do Cheque"};
                    dTM.setColumnIdentifiers(coluna);
                    break;
                }
            }//end switch
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(VPTDP_Simples.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPTDP_Completo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPTDP_Completo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPTDP_Completo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPTDP_Completo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VPTDP_Completo dialog = new VPTDP_Completo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void addDadoNaTabela(Venda venda, int tipo) {
        //Adcionada os dados da venda na tabela
        //O segundo parâmetro determina qual o tipo de pagamento da venda
        
        Object linha [] = new String[6];
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Calendar cal;
        cal = venda.getData();

        linha[0] = venda.getNumero();
        linha[1] = venda.getCliente().getNome();
        linha[2] = venda.getCliente().getCpf();
        linha[3] = sdf.format(cal.getTime());
        
        
        switch(tipo){
            case 1:{
                linha[4] = "";
                linha[5] = "";
                break;
            }
            case 2:{
                //cartão
                Cartao c = (Cartao) venda.getTipoPgto();
                linha[4] = c.getNome();
                linha[5] = c.getNumero();
                break;
            }
            case 3:{
                Cheque c = (Cheque) venda.getTipoPgto();
                linha[4] = c.getNomeEmissor();
                linha[5] = c.getNumeroCheque();
                break;
            }
        }//end switch
        dTM.addRow(linha);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoExibir;
    private javax.swing.JComboBox ComboBox;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

  
}
