# Project: TP_ED2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../algoritmos_de_busca.o ../grafos.o ../main.o ../mini_controller.o
LINKOBJ  = ../algoritmos_de_busca.o ../grafos.o ../main.o ../mini_controller.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = TP_ED2.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

../algoritmos_de_busca.o: ../algoritmos_de_busca.c
	$(CC) -c ../algoritmos_de_busca.c -o ../algoritmos_de_busca.o $(CFLAGS)

../grafos.o: ../grafos.c
	$(CC) -c ../grafos.c -o ../grafos.o $(CFLAGS)

../main.o: ../main.c
	$(CC) -c ../main.c -o ../main.o $(CFLAGS)

../mini_controller.o: ../mini_controller.c
	$(CC) -c ../mini_controller.c -o ../mini_controller.o $(CFLAGS)
